/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/audit/{audit_ref}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Audit */
        get: operations["get_audit_api_audit__audit_ref__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Decisions */
        get: operations["list_decisions_api_decisions_get"];
        put?: never;
        /**
         * Record Decision
         * @description Stage 7: capture the human decision.
         *
         *     HAVEN never actions anything itself. This endpoint records what the operator
         *     chose and why, which is also the input to the decision-learning loop.
         */
        post: operations["record_decision_api_decisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Evaluate */
        post: operations["post_evaluate_api_evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/procedures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Procedures */
        get: operations["list_procedures_api_procedures_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scenarios */
        get: operations["list_scenarios_api_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/{scenario_id}/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evaluate Scenario */
        get: operations["evaluate_scenario_api_scenarios__scenario_id__evaluate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditRecord */
        AuditRecord: {
            /** Audit Ref */
            audit_ref: string;
            /** Chain Valid */
            chain_valid: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Model Id */
            model_id: string;
            /** Provider */
            provider: string;
            /** Situation Id */
            situation_id: string;
            /** Steps */
            steps: components["schemas"]["AuditStep"][];
        };
        /** AuditStep */
        AuditStep: {
            /** Detail */
            detail: string;
            /** Duration Ms */
            duration_ms: number;
            /** Entry Hash */
            entry_hash: string;
            /**
             * Inputs
             * @default {}
             */
            inputs: {
                [key: string]: unknown;
            };
            /**
             * Outputs
             * @default {}
             */
            outputs: {
                [key: string]: unknown;
            };
            /** Prev Hash */
            prev_hash: string;
            /** Seq */
            seq: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Step */
            step: string;
            /** Tier */
            tier: string;
        };
        /** BestCandidate */
        BestCandidate: {
            /** Doc */
            doc: string;
            /** Relevance */
            relevance: number;
            /**
             * Section
             * @default
             */
            section: string;
        };
        /** Citation */
        Citation: {
            /** Doc */
            doc: string;
            /**
             * Passage Id
             * @default
             */
            passage_id: string;
            /** Section */
            section: string;
            /**
             * Title
             * @default
             */
            title: string;
        };
        /**
         * ClauseDetail
         * @description One compiled precondition, as the deterministic checker evaluated it.
         *
         *     Present on both outcomes, because both are claims about the same test: on a
         *     recommendation these clauses are the evidence the citation was lawful; on a
         *     refusal they are the reason it was not. The reasoning tier never sees this
         *     shape -- it is produced by ``haven.deterministic.preconditions`` after the
         *     model has already spoken (safety requirement S4).
         */
        ClauseDetail: {
            /** Actual */
            actual: string;
            /** Clause */
            clause: string;
            /** Expected */
            expected: string;
            /** Explanation */
            explanation: string;
            /** Satisfied */
            satisfied: boolean;
        };
        /** CrewMember */
        CrewMember: {
            /**
             * Circadian Offset H
             * @default 0
             */
            circadian_offset_h: number;
            /**
             * Duty Log
             * @default []
             */
            duty_log: components["schemas"]["DutyEntry"][];
            /**
             * Id
             * @example CM-01
             */
            id: string;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Qualified For
             * @default []
             */
            qualified_for: string[];
            /**
             * Role
             * @example commander
             */
            role: string;
            /**
             * Sleep Log
             * @default []
             */
            sleep_log: components["schemas"]["SleepEntry"][];
        };
        /**
         * CrewReadiness
         * @description Zone 1 payload: per-crew state at the moment of evaluation.
         */
        CrewReadiness: {
            /** Alertness Score */
            alertness_score: number;
            /** Asleep At Window Start */
            asleep_at_window_start: boolean;
            /** Baseline Alertness */
            baseline_alertness: number;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "moderate" | "low" | "insufficient";
            /** Crew Member */
            crew_member: string;
            /**
             * Curve
             * @default []
             */
            curve: components["schemas"]["CurvePoint"][];
            /** Data Coverage */
            data_coverage: number;
            /** Delta Vs Baseline */
            delta_vs_baseline: number;
            /** Hours Awake */
            hours_awake: number;
            /** Name */
            name: string;
            /**
             * Reference At
             * Format: date-time
             */
            reference_at: string;
            /** Role */
            role: string;
            /** Sleep Debt H */
            sleep_debt_h: number;
            /**
             * Status
             * @enum {string}
             */
            status: "nominal" | "watch" | "degraded";
            /**
             * Trend
             * @enum {string}
             */
            trend: "improving" | "stable" | "declining";
            /** Window Min Alertness */
            window_min_alertness: number;
            /**
             * Window Min At
             * Format: date-time
             */
            window_min_at: string;
            /** Workload Score */
            workload_score: number;
        };
        /** CurvePoint */
        CurvePoint: {
            /** Asleep */
            asleep: boolean;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Circadian */
            circadian: number;
            /** Homeostatic */
            homeostatic: number;
            /** In Circadian Low */
            in_circadian_low: boolean;
            /** Inertia */
            inertia: number;
            /** Kss */
            kss: number;
            /** Score */
            score: number;
        };
        /** DecisionRecord */
        DecisionRecord: {
            /** Audit Ref */
            audit_ref: string;
            /** Decision */
            decision: string;
            /** Decision Id */
            decision_id: string;
            /** Operator */
            operator: string;
            /** Reason */
            reason: string;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Situation Id */
            situation_id: string;
        };
        /** DecisionRequest */
        DecisionRequest: {
            /** Audit Ref */
            audit_ref: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "approved" | "overridden";
            /**
             * Operator
             * @default flight_surgeon_console
             */
            operator: string;
            /**
             * Reason
             * @default
             */
            reason: string;
            /** Situation Id */
            situation_id: string;
        };
        /** DutyEntry */
        DutyEntry: {
            /**
             * End
             * Format: date-time
             */
            end: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * Task Type
             * @default science_ops
             */
            task_type: string;
        };
        /** EvaluationRequest */
        EvaluationRequest: {
            /** Crew */
            crew: components["schemas"]["CrewMember"][];
            evaluation_window: components["schemas"]["EvaluationWindow"];
            /** Scenario Id */
            scenario_id?: string | null;
            /** Tasks */
            tasks: components["schemas"]["Task"][];
        };
        /** EvaluationResponse */
        EvaluationResponse: {
            /**
             * Archived Low Risk
             * @default []
             */
            archived_low_risk: string[];
            /** Evaluation Id */
            evaluation_id: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Readiness */
            readiness: components["schemas"]["CrewReadiness"][];
            /** Scenario Id */
            scenario_id?: string | null;
            /**
             * Scenario Note
             * @default
             */
            scenario_note: string;
            /**
             * Scenario Title
             * @default
             */
            scenario_title: string;
            /** Situations */
            situations: components["schemas"]["Situation"][];
            tier_status: components["schemas"]["TierStatus"];
            /** Timeline */
            timeline: components["schemas"]["TimelineTask"][];
            window: components["schemas"]["EvaluationWindow"];
        };
        /** EvaluationWindow */
        EvaluationWindow: {
            /**
             * End
             * Format: date-time
             */
            end: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
        };
        /**
         * Evidence
         * @description The deterministic facts handed to the reasoning tier, echoed verbatim.
         *
         *     Present in the response so an operator can confirm that every number in the
         *     recommendation text came from here and not from the model.
         */
        Evidence: {
            /** Circadian */
            circadian: number;
            /**
             * Data Coverage
             * @default 1
             */
            data_coverage: number;
            /** Homeostatic */
            homeostatic: number;
            /** Hours Awake */
            hours_awake: number;
            /** Inertia */
            inertia: number;
            /** Kss */
            kss: number;
            /** Last Sleep Duration H */
            last_sleep_duration_h: number;
            /** Sleep Debt H */
            sleep_debt_h: number;
            /**
             * Workload Band
             * @default
             */
            workload_band: string;
            /**
             * Workload Subscales
             * @default {}
             */
            workload_subscales: {
                [key: string]: number;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ProcedureSummary */
        ProcedureSummary: {
            /** Doc */
            doc: string;
            /** Passage Id */
            passage_id: string;
            /** Section */
            section: string;
            /** Source */
            source: string;
            /** Task Types */
            task_types: string[];
            /** Text */
            text: string;
            /** Title */
            title: string;
        };
        /** Recommendation */
        Recommendation: {
            /**
             * Action
             * @enum {string}
             */
            action: "second_operator_verify" | "short_rest_then_proceed" | "duty_rotation" | "task_deferral" | "no_action_required";
            /** Action Label */
            action_label: string;
            citation: components["schemas"]["Citation"];
            /** Rationale */
            rationale: string;
            /**
             * Resource Cost
             * @default
             */
            resource_cost: string;
            schedule_impact: components["schemas"]["ScheduleImpact"];
            /**
             * Verified Clauses
             * @default []
             */
            verified_clauses: components["schemas"]["ClauseDetail"][];
        };
        /** Refusal */
        Refusal: {
            best_candidate?: components["schemas"]["BestCandidate"] | null;
            /**
             * Checker Disagreed
             * @default false
             */
            checker_disagreed: boolean;
            /** Escalate To */
            escalate_to: string;
            /** Explanation */
            explanation: string;
            /**
             * Failed Clauses
             * @default []
             */
            failed_clauses: components["schemas"]["ClauseDetail"][];
            /** Gate */
            gate: number;
            /** Model Selected */
            model_selected?: string | null;
            /**
             * Reason
             * @enum {string}
             */
            reason: "no_governing_procedure" | "insufficient_input" | "roster_conflict" | "provider_unavailable" | "precondition_unmet" | "checker_model_disagreement" | "numeric_integrity_failure";
            /** Reason Label */
            reason_label: string;
            /** Searched */
            searched: string[];
        };
        /**
         * ScenarioSummary
         * @description One demo scenario, as listed by ``GET /api/scenarios``.
         *
         *     Declared here rather than returned as a bare ``list[dict]`` so the console's
         *     type for it is generated from the contract like everything else, instead of
         *     being hand-maintained and free to drift.
         */
        ScenarioSummary: {
            /** Demonstrates */
            demonstrates: string;
            /** Id */
            id: string;
            /** Note */
            note: string;
            /** Subtitle */
            subtitle: string;
            /** Title */
            title: string;
        };
        /** ScheduleImpact */
        ScheduleImpact: {
            /** Alternate */
            alternate?: string | null;
            /**
             * Alternate Name
             * @default
             */
            alternate_name: string;
            /** Blocked Reason */
            blocked_reason?: string | null;
            /**
             * Checked Roles
             * @default []
             */
            checked_roles: string[];
            /**
             * Note
             * @default
             */
            note: string;
            /** Roster Ok */
            roster_ok: boolean;
        };
        /** Situation */
        Situation: {
            /** Alertness Score */
            alertness_score: number;
            /** Audit Ref */
            audit_ref: string;
            /** Circadian Flag */
            circadian_flag: boolean;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "moderate" | "low" | "insufficient";
            /**
             * Corpus Manifest
             * @default
             */
            corpus_manifest: string;
            /** Crew Member */
            crew_member: string;
            /**
             * Crew Member Name
             * @default
             */
            crew_member_name: string;
            /**
             * Crew Role
             * @default
             */
            crew_role: string;
            evidence: components["schemas"]["Evidence"];
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "recommendation" | "refusal";
            recommendation?: components["schemas"]["Recommendation"] | null;
            refusal?: components["schemas"]["Refusal"] | null;
            /**
             * Risk Level
             * @enum {string}
             */
            risk_level: "nominal" | "elevated" | "critical";
            /** Situation Id */
            situation_id: string;
            /** Task */
            task: string;
            /**
             * Task Criticality
             * @enum {string}
             */
            task_criticality: "low" | "medium" | "high";
            /**
             * Task Label
             * @default
             */
            task_label: string;
            /**
             * Task Scheduled
             * Format: date-time
             */
            task_scheduled: string;
            /** Task Type */
            task_type: string;
            /** Workload Score */
            workload_score: number;
        };
        /** SleepEntry */
        SleepEntry: {
            /**
             * Sleep
             * Format: date-time
             */
            sleep: string;
            /**
             * Wake
             * Format: date-time
             */
            wake: string;
        };
        /** Task */
        Task: {
            /** Assigned To */
            assigned_to: string;
            /**
             * Criticality
             * @enum {string}
             */
            criticality: "low" | "medium" | "high";
            /**
             * Duration Min
             * @default 60
             */
            duration_min: number;
            /**
             * Id
             * @example T-119
             */
            id: string;
            /**
             * Label
             * @default
             */
            label: string;
            /**
             * Scheduled
             * Format: date-time
             */
            scheduled: string;
            /**
             * Type
             * @example orbital_burn
             */
            type: string;
        };
        /**
         * TierStatus
         * @description Zone 6 payload: which tier is live, which is mocked, which is degraded.
         */
        TierStatus: {
            /**
             * Corpus Manifest
             * @default
             */
            corpus_manifest: string;
            /**
             * Degraded
             * @default false
             */
            degraded: boolean;
            /** Degraded Reason */
            degraded_reason?: string | null;
            /** Deterministic */
            deterministic: string;
            /** Orchestration */
            orchestration: string;
            /**
             * Provider Chain
             * @default []
             */
            provider_chain: string[];
            /** Reasoning */
            reasoning: string;
            /** Retrieval */
            retrieval: string;
            /**
             * Served By
             * @default
             */
            served_by: string;
        };
        /**
         * TimelineTask
         * @description Zone 2 payload: a task plotted against predicted alertness.
         */
        TimelineTask: {
            /** Assigned Name */
            assigned_name: string;
            /** Assigned To */
            assigned_to: string;
            /** Circadian Low */
            circadian_low: boolean;
            /**
             * Criticality
             * @enum {string}
             */
            criticality: "low" | "medium" | "high";
            /** Label */
            label: string;
            /** Predicted Alertness */
            predicted_alertness: number;
            /** Raises Situation */
            raises_situation: boolean;
            /**
             * Risk Level
             * @enum {string}
             */
            risk_level: "nominal" | "elevated" | "critical";
            /**
             * Scheduled
             * Format: date-time
             */
            scheduled: string;
            /** Situation Id */
            situation_id?: string | null;
            /** Task Id */
            task_id: string;
            /** Type */
            type: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_audit_api_audit__audit_ref__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                audit_ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_decisions_api_decisions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionRecord"][];
                };
            };
        };
    };
    record_decision_api_decisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_evaluate_api_evaluate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_procedures_api_procedures_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcedureSummary"][];
                };
            };
        };
    };
    list_scenarios_api_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioSummary"][];
                };
            };
        };
    };
    evaluate_scenario_api_scenarios__scenario_id__evaluate_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
