"use client";

import { useCallback, useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, X } from "lucide-react";
import { Label } from "./ui";

/**
 * The first-run walkthrough.
 *
 * Four stops, in the order the console is meant to be read: who is running
 * low, when the collision happens, what to do about it, and how to check the
 * answer. It exists because the console is legible now but not self-evident —
 * a dial with a band on it is a new instrument, and telling somebody what they
 * are looking at once is cheaper than designing around the fact that nobody
 * told them.
 *
 * It anchors to `data-tour` attributes rather than to structure, so moving a
 * card in the layout cannot silently point the tour at the wrong thing: the
 * attribute either exists or the step is skipped.
 *
 * Shown once, remembered in localStorage, and replayable from the masthead —
 * a tour you cannot get back is a tour you have to sit through.
 */

const KEY = "haven.tour.v1";

interface Stop {
  target: string;
  title: string;
  body: string;
  /** Which side of the target the card prefers. */
  side: "right" | "left" | "below";
}

const STOPS: Stop[] = [
  {
    target: "crew",
    title: "Who is running low",
    body: "One dial per crew member: predicted alertness against that person's own baseline, so an ordinary individual difference is not mistaken for a warning sign. Pick anyone to put their day on the dial.",
    side: "below",
  },
  {
    target: "dial",
    title: "The day, as a clock",
    body: "Twenty-four hours around the circle, midnight at the top. The glowing band is predicted alertness — the further from the centre, the sharper the operator. Each dot is a scheduled task, sitting at its hour and at the height of the curve there. A dot low on the dial is a hard job landing in a bad hour.",
    side: "right",
  },
  {
    target: "verdict",
    title: "What HAVEN recommends",
    body: "The action, one plain sentence saying why, and the four figures behind it — every one computed by ordinary maths, never generated by the model. When no procedure governs the situation, this card refuses and escalates instead of guessing. That is a correct answer, not a failure.",
    side: "left",
  },
  {
    target: "audit",
    title: "Check it, don't trust it",
    body: "Every step is logged and hash-chained, so an altered entry stops verifying. Open any panel marked with a chevron for the full evidence: the candidate rules, the checker's verdict clause by clause, and the timings. Nothing here is hidden — it is folded.",
    side: "below",
  },
];

interface Rect {
  top: number;
  left: number;
  width: number;
  height: number;
}

export function Tour({ open, onClose }: { open: boolean; onClose: () => void }) {
  const [index, setIndex] = useState(0);
  const [rect, setRect] = useState<Rect | null>(null);

  const stop = STOPS[index];

  const measure = useCallback(() => {
    const node = document.querySelector<HTMLElement>(`[data-tour="${stop.target}"]`);
    if (!node) {
      setRect(null);
      return;
    }
    const box = node.getBoundingClientRect();
    setRect({ top: box.top, left: box.left, width: box.width, height: box.height });
  }, [stop.target]);

  // Bring the step's subject into view before measuring it, or the spotlight
  // lands on something the reader cannot see.
  useEffect(() => {
    if (!open) return;
    const node = document.querySelector<HTMLElement>(`[data-tour="${stop.target}"]`);
    node?.scrollIntoView({ block: "center", behavior: "smooth" });
    const settle = window.setTimeout(measure, 420);
    return () => window.clearTimeout(settle);
  }, [open, stop.target, measure]);

  useEffect(() => {
    if (!open) return;
    window.addEventListener("resize", measure);
    window.addEventListener("scroll", measure, true);
    return () => {
      window.removeEventListener("resize", measure);
      window.removeEventListener("scroll", measure, true);
    };
  }, [open, measure]);

  const finish = useCallback(() => {
    try {
      window.localStorage.setItem(KEY, "done");
    } catch {
      // A browser refusing storage is not a reason to trap somebody in a tour.
    }
    setIndex(0);
    onClose();
  }, [onClose]);

  useEffect(() => {
    if (!open) return;
    const onKey = (event: KeyboardEvent) => {
      if (event.key === "Escape") finish();
      if (event.key === "ArrowRight")
        setIndex((i) => (i + 1 < STOPS.length ? i + 1 : i));
      if (event.key === "ArrowLeft") setIndex((i) => Math.max(0, i - 1));
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [open, finish]);

  if (!open) return null;

  const pad = 10;
  const card = cardPosition(rect, stop.side);

  return (
    <div className="fixed inset-0 z-[60]" role="dialog" aria-modal="true" aria-label="Console tour">
      {/* The spotlight. One element, and the dimming is its shadow — which is
          how you get a hole in an overlay without clip-path arithmetic. */}
      {rect ? (
        <div
          className="pointer-events-none absolute rounded-[22px] transition-all duration-500"
          style={{
            top: rect.top - pad,
            left: rect.left - pad,
            width: rect.width + pad * 2,
            height: rect.height + pad * 2,
            boxShadow:
              "0 0 0 9999px rgba(4,3,12,0.74), inset 0 0 0 1px rgba(189,166,255,0.5), 0 0 60px -10px rgba(150,110,255,0.5)",
          }}
        />
      ) : (
        <div className="absolute inset-0" style={{ background: "rgba(4,3,12,0.74)" }} />
      )}

      <div
        className="glass rise absolute w-[min(360px,calc(100vw-2rem))] p-5"
        style={{ ...card, borderRadius: "var(--radius-lg)" }}
      >
        <div className="flex items-start gap-3">
          <div className="min-w-0 flex-1">
            <Label>
              Step {index + 1} of {STOPS.length}
            </Label>
            <h2 className="display mt-1.5 text-[21px] text-[var(--ink)]">{stop.title}</h2>
          </div>
          <button
            onClick={finish}
            aria-label="Skip the tour"
            className="glass-3 glass-interactive shrink-0 rounded-full p-1.5 text-[var(--ink-2)] hover:text-[var(--ink)]"
          >
            <X size={14} />
          </button>
        </div>

        <p className="mt-3 text-[13px] leading-relaxed text-[var(--ink-2)]">{stop.body}</p>

        <div className="mt-5 flex items-center gap-2">
          <div className="flex flex-1 gap-1.5" aria-hidden>
            {STOPS.map((s, i) => (
              <span
                key={s.target}
                className="h-[3px] flex-1 rounded-full transition-colors duration-300"
                style={{
                  background: i <= index ? "var(--iris)" : "rgba(255,255,255,0.14)",
                  boxShadow: i <= index ? "0 0 8px -1px var(--iris)" : undefined,
                }}
              />
            ))}
          </div>
          {index > 0 ? (
            <button
              onClick={() => setIndex((i) => Math.max(0, i - 1))}
              className="glass-3 glass-interactive rounded-full p-2 text-[var(--ink-2)] hover:text-[var(--ink)]"
              aria-label="Previous step"
            >
              <ArrowLeft size={14} />
            </button>
          ) : null}
          {index + 1 < STOPS.length ? (
            <button
              onClick={() => setIndex((i) => i + 1)}
              className="glass-interactive flex items-center gap-2 rounded-full px-4 py-2 text-[13px] font-medium"
              style={{
                color: "var(--iris)",
                background: "color-mix(in oklab, var(--iris) 18%, transparent)",
                boxShadow: "inset 0 0 0 1px color-mix(in oklab, var(--iris) 45%, transparent)",
              }}
            >
              Next
              <ArrowRight size={14} />
            </button>
          ) : (
            <button
              onClick={finish}
              className="glass-interactive rounded-full px-4 py-2 text-[13px] font-medium"
              style={{
                color: "var(--ok)",
                background: "color-mix(in oklab, var(--ok) 18%, transparent)",
                boxShadow: "inset 0 0 0 1px color-mix(in oklab, var(--ok) 45%, transparent)",
              }}
            >
              Start using it
            </button>
          )}
        </div>
      </div>
    </div>
  );
}

/**
 * Put the card beside its subject, and inside the viewport.
 *
 * The preferred side is a preference: on a narrow screen every side is the
 * wrong one, so it falls back to pinning the card to the bottom of the screen
 * where it can never cover the thing it is describing off-screen.
 */
function cardPosition(rect: Rect | null, side: Stop["side"]) {
  const cardW = Math.min(360, window.innerWidth - 32);
  const gap = 18;

  if (!rect || window.innerWidth < 900) {
    return { left: (window.innerWidth - cardW) / 2, bottom: 24 } as const;
  }

  const clampTop = (top: number) => Math.max(16, Math.min(window.innerHeight - 300, top));

  if (side === "right" && rect.left + rect.width + gap + cardW < window.innerWidth) {
    return { left: rect.left + rect.width + gap, top: clampTop(rect.top) };
  }
  if (side === "left" && rect.left - gap - cardW > 0) {
    return { left: rect.left - gap - cardW, top: clampTop(rect.top) };
  }
  // Below, or above if there is no room below.
  const below = rect.top + rect.height + gap;
  if (below + 260 < window.innerHeight) {
    return { left: Math.min(rect.left, window.innerWidth - cardW - 16), top: below };
  }
  return {
    left: Math.min(rect.left, window.innerWidth - cardW - 16),
    top: clampTop(rect.top - 260 - gap),
  };
}

/** Has this browser seen the tour? Read once, on mount, by the console. */
export function tourSeen() {
  try {
    return window.localStorage.getItem(KEY) === "done";
  } catch {
    return true;
  }
}
